### PR TITLE
[GRIFFIN] acdbdata: Rectify Handset calibration

### PR DESCRIPTION
**Pull request by kholk**
This file was corrupted: copy back the clean one.

### CODE REVIEW

**Comment by Paulbouchara** [comment]
MERGEME

**Comment by MarijnS95** [comment]
We're constantly asking new contributors to include logs or other information that backs up their reasoning behind a certain change. Let's set a good example ourselves.

```
07-15 07:28:32.509   789 16780 E ACDB-LOADER: ACDB -> Not correctly initialized!
```

**Comment by MarijnS95** [comment]
Upon closer inspection this is a revert of https://github.com/sonyxperiadev/device-sony-griffin/commit/e4b7041. The md5sum before that and of a recent stock release (`55.1.A.3.149`) is identical:

`05b85c683acf326ebeeb43e7c3cebc1f  rootdir/vendor/etc/acdbdata/Handset_cal.acdb`

**Comment by kholk** [comment]
Well, either merge this or revert that, I don't care... :p

**Comment by kholk** [comment]
I've PRed to the wrong branch. Recreating the PR.

**Comment by MarijnS95** [comment]
You know you can change the target branch, right???

Github hid it behind the "edit" button right after the title, though.

(Now that you're pushing again anyway, do the revert 😉)

**Pull request closed without merging**
